### ISSUE TITLE
params not working with swagger-ui

### ISSUE THREAD

**Issue by edossantos** [elixir-maru/maru_swagger#10]
hello there,
I wanted to know why on swagger-ui it doesn't show the params. it only shows a body.
![swagger ui](https://cloud.githubusercontent.com/assets/4502334/13541749/355ab98e-e22c-11e5-83da-9d1f7a250c6d.png)

**Comment by falood** [comment]
Could you please show me your code within `params do end` block?

**Comment by edossantos** [comment]
`defmodule MyAppApi.API.Router do
  use Maru.Router

  get do
     conn |> text("API works Swagger!")
 end
  resource :user do
    # desc "description"
    get do
      text(conn, "Router: v1")
    end
    # desc "description"
    params do
      requires :name, type: String
    end
    post do
      text(conn, "Router: v1 Post")
    end
  end

  namespace :create_user do
            desc "Create new user"
            params do
              requires :name, type: String
              requires :email, type: String
              requires :password, type: String
            end
            post do
                  text(conn, "Router: v1 Params")
            end
   end
end`


-----------------------------
`defmodule MyAppApi.API do
  use Maru.Router
  plug Plug.RequestId
  plug Plug.Logger
  resources do
     mount MyAppApi.API.Router
   end

  if Mix.env == :dev do
    plug MaruSwagger,
      at:      "/swagger",
      for:     MyAppApi.API,
      pretty:  true
  end

  rescue_from Unauthorized, as: e do
   IO.inspect e
   status 401
   "Unauthorized"
  end

  rescue_from :all, as: e do
   IO.inspect e
   status 500
   "Server Error"
  end

  get do
     conn |> text("API works!")
 end




end`

**Comment by falood** [comment]
I try this locally and it works fine.
It seems that an outdate version `maru` or `maru_swagger` was used in your case.
Update both to latest version and try again, please.

**Comment by edossantos** [comment]
I'm using those versions. I believe thats the latest version? no?
 {:maru, "~> 0.9"},
 {:maru_swagger, "~> 0.7", only: :dev}

**Comment by falood** [comment]
![image](https://cloud.githubusercontent.com/assets/184053/13657754/aecbbc12-e6ac-11e5-83b2-027f2bbc3004.png)
It's strange.
This is my `mix.lock` file, any difference?

**Comment by edossantos** [comment]
cat mix.lock
%{"connection": {:hex, :connection, "1.0.2"},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "csv": {:hex, :csv, "1.2.4"},
  "db_connection": {:hex, :db_connection, "0.2.4"},
  "decimal": {:hex, :decimal, "1.1.1"},
  "ecto": {:hex, :ecto, "2.0.0-beta.2"},
  "fs": {:hex, :fs, "0.9.2"},
  "geo": {:git, "https://github.com/bryanjos/geo.git", "6a11ec15ed14870ff06322c9667d713aa39720b7", []},
  "gettext": {:hex, :gettext, "0.10.0"},
  "maru": {:hex, :maru, "0.9.4"},
  "maru_swagger": {:hex, :maru_swagger, "0.7.2"},
  "phoenix": {:hex, :phoenix, "1.1.4"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "3.0.0-beta.2"},
  "phoenix_html": {:hex, :phoenix_html, "2.5.0"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.3"},
  "plug": {:hex, :plug, "1.1.2"},
  "poison": {:hex, :poison, "2.1.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.11.1"},
  "ranch": {:hex, :ranch, "1.2.1"}}

**Comment by falood** [comment]
I'm so sorry that I tried your code locally again and again and I couldn't catch any error.

**Comment by falood** [comment]
Hi, 
maru v0.10 and maru_swagger v0.8 are out.
I did lots of compatibility with phoenix and [here](https://github.com/falood/maru_examples/blob/f27ceb785953c928ca7f7e20914d78a1cf6133d1/phoenix_maru/web/apis/homepage.ex) is an example.
You can try it if you're still using maru and maru_swagger.
sorry for the lated update.

**Comment by falood** [comment]
Hi man, could I close this issue now?
